### PR TITLE
Added new model

### PR DESCRIPTION
**Pull request by lvaleriu**

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Thanks for PR. A few notes..
* Other models have the summary w.r.t. the symbols in the tutorial paper. Could you add this, too?
```python
      Symbolic summary:
     > c1 - p1 - c1 - p1 - c1 - p1 - p3 - d1
```

* Is there any reference on this model? Otherwise perhaps model.summary()? 
* Do we need `dropout()` between LSTMs? Even so, I think 0.5 is quite a large number. 
* So is the size of LSTM hidden memory. Something between 32-64 would be better, at least for the educational purpose. All 32/48/64 sounds good, or any arbitrary number that doesn't appear in other dimension along the layers would be also make thing easier to understand.

**Comment by lvaleriu** [comment]
Hello. I've just did some modifications. Are they more suitable right now?

**Comment by keunwoochoi** [comment]
Yes they are, still there're few things.
- [Commented](https://github.com/keunwoochoi/dl4mir/pull/8/files/edc9c9191f830e9cc8a29bd08e7004fe859c3e62..9dc9e34ab3fa87b50e812994f0aff67e8bef0c50#diff-ddba4d9501c873aff2d9d17151b0334cR329) line should be removed
- The symbol summary omitted recurrent part (r1 I think)
- Perhaps it'd help to make it explicit that what's common/different with CRNN? e.g. it is CRNN, but some conv layers are 1d (and why), it doesn't summarise them all using recurrent layer but use merge (and also why). Otherwise I'm afraid beginners wouldn't get why it is here. I'd also like to know the reasons behind design choices.

**Comment by lvaleriu** [comment]
PR updated. I’ve tried to follow your guidance direction

**Comment by keunwoochoi** [comment]
Thanks. But I'm still not convinced why the structure should be part of the repo. It's fairly similar to CRNN -- it actually is CRNN with conv1d, which I expect would not show any better performance. I also don't particularly agree with the design choice of LSTM then averaging -- especially when LSTM is not bi-directional. All that said, as a tutorial, I would need clearer justification/explanation of a structure. Thanks though.

**Pull request closed without merging**
